#! /bin/bash

PATH=$HOME/bin/public:$HOME/bin/private
PATH=$PATH:$HOME/.cabal/bin
PATH=$PATH:$HOME/.gem/bin
PATH=$PATH:/bin:/usr/bin:/sbin:/usr/sbin
PATH=$PATH:/opt/java/bin
PATH=$PATH:/opt/android-sdk/tools:/opt/android-sdk/platform-tools
PATH=$PATH:/usr/bin/vendor_perl
export PATH

export EDITOR=/usr/bin/vim

if [[ -z "$DISPLAY" ]] && [[ ! -a "/tmp/.X11-unix/X0" ]] && [[ $(tty) = /dev/tty1 ]]
then
  (xinit -- /usr/bin/Xorg -nolisten tcp &)
  exit
fi

eval $(keychain --eval --nogui -q id_rsa D44C440C)
