set nocompatible
set nobackup nowritebackup noswapfile viminfo=
set notitle showmode showcmd number ruler
set noerrorbells visualbell t_vb=
"set ttyfast lazyredraw
set wildmenu complete+=k
set backspace=indent,eol,start
set encoding=utf-8
set nojoinspaces
set nomodeline

set ttymouse=xterm2
set mouse=a " for scroll wheel. do normal term copying by holding shift
set clipboard=unnamed

set guioptions=aegirLt

filetype plugin indent on

" - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

let mapleader = ","

imap jj <esc>

nmap <leader>ww :w<cr>

map <leader>sv :source ~/.vimrc<cr>

nmap <silent> <f2> :Sexplore<cr>

function! BrianReplaceWord(word0, word1)
  let l:pos = getpos(".")
  exec "%s/\\<" . a:word0 . "\\>/" . a:word1 . "/g"
  call setpos('.', l:pos)
endfunction
nmap <f4> :call BrianReplaceWord("<c-r><c-w>", "")<Left><Left>

nmap <silent> <f6> :bp<cr>
nmap <silent> <f7> :bn<cr>
nmap <silent> <f8> :bd<cr>

" nice pasting from clipboard
imap <leader>v <c-o>mz<c-o>:set paste<cr><c-r>*<c-o>:set nopaste<cr><c-o>`z
nmap <leader>v mz:set paste<cr>"*P:set nopaste<cr>`z

nmap <silent> <leader>ss :setlocal spell!<cr>
set spelllang=en

" - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

" keep cursor in place when joining lines with J
nnoremap J mzJ`z

" center window automatically after jumps
nnoremap n nzz
nnoremap N Nzz
nnoremap } }zz
nnoremap { {zz

nnoremap <f1> <nop>
nnoremap Q    <nop>
nnoremap K    <nop>

" - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

let g:netrw_list_hide = "^\\..*$"

set laststatus=2
" let g:obviousModeInsertHi = 'term=reverse ctermfg=15 ctermbg=18'

syntax on

"highlight Search guifg=NONE ctermfg=NONE gui=none cterm=none
highlight SpellBad ctermbg=17 ctermfg=15
highlight SpellCap ctermbg=17 ctermfg=15

set autoindent smartindent
set shiftwidth=2 tabstop=2 expandtab
set nowrap

set list listchars=tab:»·,trail:·

set cinoptions =:0  " don't indent 'case' in 'switch'
set cinoptions+=ls  " regular alignment of {} in 'case'
set cinoptions+=(s  " regular indentation after trailing (
set cinoptions+=m1  " deindent closing )

" - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

" auto-resize splits window is resized
au VimResized * exe "normal! \<c-w>="

set splitbelow splitright

" - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

highlight ShowTrailingWhitespace ctermbg=darkred
let g:ShowTrailingWhitespace = 1

let g:DeleteTrailingWhitespace = 0
nnoremap <leader>d$ :<c-u>%DeleteTrailingWhitespace<cr>
vnoremap <leader>d$ :DeleteTrailingWhitespace<cr>

" - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

" use <leader>W instead of <leader>w
nmap <leader>W          <plug>VimwikiIndex
nmap <leader>Wt         <plug>VimwikiTabIndex
nmap <leader>Ws         <plug>VimwikiUISelect
nmap <leader>Wi         <plug>VimwikiDiaryIndex
nmap <leader>W<leader>i <plug>VimwikiDiaryGenerateLinks
nmap <leader>W<leader>t <plug>VimwikiTabMakeDiaryNote
nmap <leader>W<leader>w <plug>VimwikiMakeDiaryNote

let g:vimwiki_list = [{'path': '~/data/vimwiki'}]

" - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'

Bundle 'Align'
"Bundle 'Lokaltog/vim-powerline'
Bundle 'Lokaltog/powerline'
Bundle 'gnupg.vim'
Bundle 'localvimrc'
Bundle 'tpope/vim-afterimage'
Bundle 'tpope/vim-commentary'
Bundle 'tpope/vim-markdown'
Bundle 'tpope/vim-repeat'
Bundle 'tpope/vim-surround'
Bundle 'vimwiki'
Bundle 'ShowTrailingWhitespace'
Bundle 'DeleteTrailingWhitespace'
Bundle 'ctrlp.vim'
Bundle 'phd'
Bundle 'jellybeans.vim'

" - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

source ~/.vim/bundle/powerline/powerline/bindings/vim/plugin/source_plugin.vim

colorscheme jellybeans

if exists('&colorcolumn')
  set colorcolumn=+1
  hi ColorColumn ctermbg=darkred guibg=darkred
endif
