set nocompatible
set nobackup nowritebackup noswapfile viminfo=
set notitle showmode showcmd number ruler
set noerrorbells visualbell t_vb=
"set ttyfast lazyredraw
set wildmenu complete+=k
set backspace=indent,eol,start
set encoding=utf-8
set nojoinspaces
set nomodeline
set scrolloff=4
set noesckeys
set shell=sh
set hlsearch incsearch
set cursorline
set textwidth=96
set ttimeoutlen=50

set ttymouse=xterm2
set mouse=a " for scroll wheel. do normal term copying by holding shift

set guioptions=aegirLt

filetype plugin indent on

" - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

let mapleader = ","

imap jj <esc>

nmap <cr> :write<cr>

map <leader>sv :source ~/.vimrc<cr>

" sort a block, like Java import statements
nmap <silent> <f2> mzvip:sort<cr>`z:echo "### Sorted!!! ###"<cr>
vmap <silent> <f2> mz:sort<cr>`z:echo "### Sorted!!! ###"<cr>

function! BrianReplaceWord(word0, word1)
  let l:pos = getpos(".")
  exec "%s/\\<" . a:word0 . "\\>/" . a:word1 . "/g"
  call setpos('.', l:pos)
endfunction
nmap <f4> :call BrianReplaceWord("<c-r><c-w>", "")<Left><Left>

nmap <silent> <f5> :tabmove -1<cr>
nmap <silent> <f6> :tabmove +1<cr>

" move left/right in tabs
nmap <silent> <f7> gT<cr>
nmap <silent> <f8> gt<cr>

" move left/right in buffers
nmap <silent> <f9>  :bp<cr>
nmap <silent> <f10> :bn<cr>

nmap <silent> <f11> :bd<cr>

" nice pasting from clipboard
imap <leader>v <c-o>mz<c-o>:set paste<cr><c-r>*<c-o>:set nopaste<cr><c-o>`z
nmap <leader>v mz:set paste<cr>"*P:set nopaste<cr>`z

nmap <silent> <leader>ss :setlocal spell!<cr>
set spelllang=en

noremap <c-h> <c-w>h
noremap <c-l> <c-w>l
noremap <c-j> <c-w>j
noremap <c-k> <c-w>k

nmap <silent> <f12> :noh<cr>

" - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

" keep cursor in place when joining lines with J
nnoremap J mzJ`z

" center window automatically after jumps
nnoremap n nzz
nnoremap N Nzz
nnoremap } }zz
nnoremap { {zz

nnoremap <f1> <nop>
nnoremap Q    <nop>
nnoremap K    <nop>

" - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

let g:netrw_list_hide = "^\\..*$"

set laststatus=2
" let g:obviousModeInsertHi = 'term=reverse ctermfg=15 ctermbg=18'

syntax on

"highlight Search guifg=NONE ctermfg=NONE gui=none cterm=none
highlight SpellBad ctermbg=17 ctermfg=15
highlight SpellCap ctermbg=17 ctermfg=15

set shiftwidth=2 tabstop=2 expandtab
set nowrap

set list listchars=tab:»·,trail:·

" set cinoptions+=>2
set cinoptions+=:0  " don't indent 'case' in 'switch'
set cinoptions+=ls  " regular alignment of {} in 'case'
set cinoptions+=(s  " regular indentation after trailing (
set cinoptions+=m1  " deindent closing )
set cinoptions+=j1  " indent Java anonymous classes correctly
set cinoptions+=J1  " indent Javascript object declarations correctly

" - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

" auto-resize splits window is resized
au VimResized * exe "normal! \<c-w>="

set splitbelow splitright

" - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

highlight ShowTrailingWhitespace ctermbg=darkred
let g:ShowTrailingWhitespace = 1

let g:DeleteTrailingWhitespace = 0
nnoremap <leader>d$ :<c-u>%DeleteTrailingWhitespace<cr>
vnoremap <leader>d$ :DeleteTrailingWhitespace<cr>

" - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

" use <leader>W instead of <leader>w
nmap <leader>W          <plug>VimwikiIndex
nmap <leader>Wt         <plug>VimwikiTabIndex
nmap <leader>Ws         <plug>VimwikiUISelect
nmap <leader>Wi         <plug>VimwikiDiaryIndex
nmap <leader>W<leader>i <plug>VimwikiDiaryGenerateLinks
nmap <leader>W<leader>t <plug>VimwikiTabMakeDiaryNote
nmap <leader>W<leader>w <plug>VimwikiMakeDiaryNote

let g:vimwiki_list = [{'path': '~/data/vimwiki'}]

" - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'

Bundle 'Align'
Bundle 'Command-T'
Bundle 'DeleteTrailingWhitespace'
Bundle 'EasyMotion'
Bundle 'ShowTrailingWhitespace'
Bundle 'Valloric/YouCompleteMe'
Bundle 'bling/vim-airline'
Bundle 'bufkill.vim'
Bundle 'closetag.vim'
Bundle 'gnupg.vim'
Bundle 'goldfeld/vim-seek'
Bundle 'jellybeans.vim'
Bundle 'tpope/vim-afterimage'
Bundle 'tpope/vim-commentary'
Bundle 'tpope/vim-markdown'
Bundle 'tpope/vim-repeat'
Bundle 'tpope/vim-surround'
Bundle 'vimwiki'

let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'

" - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

colorscheme jellybeans

if exists('&colorcolumn')
  set colorcolumn=+1
  hi ColorColumn ctermbg=darkred guibg=darkred
endif
