#!/bin/bash

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

[ -f ~/.Xresources ] && xrdb -merge ~/.Xresources

xset +fp /usr/share/fonts/local  # terminus
xset fp rehash

# speed up keyboard repeat
xset r rate 200 50

# make caps lock another ctrl key
setxkbmap -option ctrl:nocaps

xbacklight -set 65
disable-screen-blanking

xsetroot -solid '#0f0f0f'

export XMODIFIERS="@im=SCIM"
export GTK_IM_MODULE="scim"
export QT_IM_MODULE="scim"
scim -d

urxvtd -q -f -o

exec awesome
